POST http://localhost:5000/api/leagues
Content-Type: application/json

{
   "name": "League of Legends",
   "location": {
      type: "Point",
      coordinates: [-73.856077, 40.848447]
   },
   "price": 2000
}